server:
  port:
    9595

spring:
  application:
    name: customer
  datasource:
    username: 'rootuser'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'rootpass'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl_auto: create-drop
    show_sql: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9597/eureka
